version: '3.4'

services:
  rabbit-mq:
    image: rabbitmq:3.8.14-management
    container_name: rabbit-mq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq/